train_dataset:
  dataset:
    name: hr_data_loader
    args:
#      root_path: /data/kyanchen/datasets/UC/256
#      split_file: data_split/UC_split.json
      root_path: /data/kyanchen/datasets/AID
      split_file: data_split/AID_split.json
      split_key: train
      cache: none
  wrapper:
    name: inr_range_scale_sr_warp
    args:
      max_scale_ratio: 5
      patch_size: 48
      augment: true
      sample_q: 1024
      val_mode: false
      test_mode: false
      return_cell: true
  batch_size: 64
  num_workers: 4

val_dataset:
  dataset:
    name: hr_data_loader
    args:
#      root_path: /data/kyanchen/datasets/UC/256
#      split_file: data_split/UC_split.json
      root_path: /data/kyanchen/datasets/AID
      split_file: data_split/AID_split.json
      split_key: val
      first_k: 128
      cache: none
  wrapper:
    name: inr_range_scale_sr_warp
    args:
      max_scale_ratio: 5
      patch_size: 48
      augment: false
      sample_q: 1024
      val_mode: true
      test_mode: false
      return_cell: true
  batch_size: 64
  num_workers: 4

eval_type: psnr+ssim

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: metasr
  args:
    encoder_spec:
#      name: edsr-baseline
#      name: rdn
      name: rcan
      args:
        no_upsampling: true

optimizer:
  name: adamw
  args:
    lr: 1.e-4

epoch_max: 3000

lr_scheduler:
#  name: CosineAnnealingLR
#  T_max: 1500
#  eta_min: 1.e-7
  name: MultiStepLR
  milestones: [2000]
  gamma: 0.1

epoch_val_interval: 40
epoch_save_interval: 300
